sniffles_call:
    nodes: 1 
    threads: 8
    mem_mb: 36000
    time: 4320

cutesv_call:
    nodes: 1 
    threads: 12
    mem_mb: 42000
    time: 10080

svim_call:
    nodes: 1 
    threads: 4
    mem_mb: 36000
    time: 10080

vcf_merge:
    nodes: 1 
    threads: 1
    mem_mb: 24000
    time: 4320

jas_merge:
    nodes: 1 
    threads: 8
    mem_mb: 96000
    time: 10080

vcf_filter:
    nodes: 1 
    threads: 1
    mem_mb: 24000
    time: 4320

force_call:
    nodes: 1 
    threads: 8
    mem_mb: 36000
    time: 4320

final_call:
    nodes: 1
    threads: 8
    mem_mb: 64000
    time: 10080
