__default__:
    partition: "shared"
    time: 720
    nodes: 1
    output: "logs/slurm-%j.out"
    error: "logs/slurm-%j.err"

snifflesCall:
    partition: "serial_requeue,shared" 
    output: "logs/sniffcall-%j.out"
    error: "logs/sniffcall-%j.err"
    job-name: "sniffcall"

cutesvCall:
    partition: "holy-cow,shared" 
    output: "logs/cutecall-%j.out"
    error: "logs/cutecall-%j.err"
    job-name: "cutecall"

svimCall:
    partition: "holy-cow,shared" 
    output: "logs/svimcall-%j.out"
    error: "logs/svimcall-%j.err"
    job-name: "svimcall"